### ISSUE TITLE
Requires Node.js v10.0.0+

### ISSUE THREAD

**Issue by HugoPoi** [webpro/bron#1]
This package doesn't work with Node v8.x because of `isPromise` being introduce in 10.x https://nodejs.org/dist/latest-v10.x/docs/api/util.html#util_util_types_ispromise_value

and also `doesNotReject` take a function until 10.x
https://nodejs.org/docs/latest-v10.x/api/assert.html#assert_assert_doesnotreject_asyncfn_error_message

Change the readme in consequence.

**Comment by webpro** [comment]
Currently, v2 has the correct requirements:

https://github.com/webpro/bron/blob/b3d77af62c461d28cc2a3490c001bf353306489c/package.json#L38
