### ISSUE TITLE
Bron exits with exit code 0 if there is an error thrown outside a test() function

### ISSUE THREAD

**Issue by j-ulrich** [webpro/bron#2]
When running bron on a file which throws an error outside a `test()` function, bron prints the error to the console but then exits with code 0.

That's bad when running bron in a CI because the CI reports everything is fine but actually no tests were run.

To reproduce this, simply run
```
npx bron brokenFile.js
```
where `brokenFile.js` contains for example
```js
const foo = require( 'some-missing-module' );
```
or simply
```js
foo
```

**Comment by webpro** [comment]
Apologies for the late reply. The fix is in v2.0.3, thanks for reporting!
